
identifiers: 
  task: test_cert 
  
topics:
  - topic_name: /offload_detection/profile/cloud
    topic_type: offload_detection/msg/Profile
  - topic_name: /offload_detection/scheduler_yolo/input/cloud
    topic_type: sensor_msgs/msg/CompressedImage
  - topic_name: /offload_detection/scheduler_yolo/output/cloud
    topic_type: sensor_msgs/msg/CompressedImage
  - topic_name: /fogros_sgc/profile
    topic_type: sgc_msgs/msg/Profile
  - topic_name: /fogros_sgc/assignment_update
    topic_type: sgc_msgs/msg/AssignmentUpdate


state_machine: 
  standby: 
    topics:
      - /fogros_sgc/profile: pub
      - /fogros_sgc/assignment_update: sub
  service: 
    topics:
      - /offload_detection/profile/cloud: pub
      - /offload_detection/scheduler_yolo/input/cloud: sub 
      - /offload_detection/scheduler_yolo/output/cloud: pub 
      - /fogros_sgc/profile: pub
      - /fogros_sgc/assignment_update: sub
  robot: 
    topics:
      - /offload_detection/profile/cloud: sub
      - /offload_detection/scheduler_yolo/input/cloud: pub 
      - /offload_detection/scheduler_yolo/output/cloud: sub 
      - /fogros_sgc/profile: sub
      - /fogros_sgc/assignment_update: pub

assignment:
  robot: robot
  machine_local: service
  machine_cloud: standby

time_bound:
  mean_latency: 0.05
  # std_latency: 0.1
  # median_latency: 0.3
  # max_latency: 0.5
  # min_latency: 0.1