
identifiers: 
  task: test_cert 
  
topics:
  - topic_name: /chatter
    topic_type: std_msgs/msg/String
  - topic_name: /cpu_global
    topic_type: std_msgs/msg/String
  - topic_name: /cpu_top
    topic_type: std_msgs/msg/String
  - topic_name: /cpu_select
    topic_type: std_msgs/msg/String

state_machine: 
  standby: 
    topics:
      - /cpu_global: pub 
      - /cpu_top: pub 
      - /cpu_select: pub 
  service: 
    topics:
      - /cpu_global: pub 
      - /cpu_top: pub 
      - /cpu_select: pub 
      - /chatter: sub 
  robot:
    topics:
    # robot needs to subscribe to the cpu messages from the services 
      - /cpu_global: sub 
      - /cpu_top: sub 
      - /cpu_select: pub 
      - /chatter: pub

assignment:
  robot: robot
  machine_local: service
  machine_cloud: standby