identifiers: 
  task: test_cert 

services:
  - service_name: /gqcnn
    service_type: gqcnn_interfaces/srv/GqCnnGrasp

state_machine: 
  standby: 
  client: 
    services:
      - /gqcnn: client 
  server: 
    services:
      - /gqcnn: service 
      
# EXAMPLE #1: 2 servers and 1 client
assignment:
  machine_client: client
  machine_server: server

topology:
  machine_client:
    children: 
      - machine_server

# EXAMPLE #2: server -> switch -> client 
# assignment: 
#   machine_client: client
#   machine_server: server
#   machine_switch: standby

# topology:
#   machine_client:
#     children: 
#       - machine_switch:
#           children: 
#             - machine_server