debug = true
log_level = "info"
channel_size = 100
tcp_port = "9997"
dtls_port = "9232"
grpc_port = "50051"
ros_protocol="dtls"
crypto_name="e00ac"
peer_with_gateway = false
default_gateway = "128.32.37.48"
[[ros]]
local = "sub"
node_name = "benchmark_talker"
topic_name = "/benchmark"
topic_type = "std_msgs/msg/String"
[[ros]]
local = "pub"
node_name = "benchmark_listener"
topic_name = "/benchmark_echo"
topic_type = "std_msgs/msg/String"
[database]
url = "custom database url"